import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText, Output } from "ai";
import { Router, type Request, type Response } from "express";
import { z } from "zod";

import { env } from "#src/config/env";
import { requireAuth } from "#src/middlewares/auth";

const router = Router();

const MODELS = {
  GEMINI_3_PRO_PREVIEW: "gemini-3-pro-preview",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

const continuationSchema = z.object({
  san: z.string(),
  uci: z.string(),
  beforeFen: z.string(),
  afterFen: z.string(),
  color: z.enum(["white", "black"]),
});

const explainRequestSchema = z.object({
  move: z.object({
    san: z.string(),
    beforeFen: z.string(),
    afterFen: z.string(),
  }),
  badContinuation: z.array(continuationSchema),
  bestContinuation: z.array(continuationSchema).min(1),
  color: z.enum(["white", "black"]),
  userColor: z.enum(["white", "black"]).optional(), // Color the user is playing as
  moveQuality: z.enum(["blunder", "mistake", "inaccuracy", "good", "brilliant"]).optional(),
  mate: z.number().optional().default(0),
  opening: z.string().optional(),
  eco: z.string().optional(),
  additionalContext: z.string().optional(),
});

const explainResponseSchema = z.object({
  explanation: z.string(),
  badContinuation: z.array(
    z.object({
      move: z.string(),
      color: z.enum(["white", "black"]),
      reason: z.string(),
    })
  ),
  bestContinuation: z.array(
    z.object({
      move: z.string(),
      color: z.enum(["white", "black"]),
      reason: z.string(),
    })
  ),
});

const systemPrompt = `
You are a chess coach explaining Stockfish's analysis to a student. Your role is to TRANSLATE the engine's evaluation into human understanding, NOT to calculate moves yourself.

CRITICAL INSTRUCTIONS:
1. You will receive TWO continuations, both FRESHLY GENERATED by Stockfish:
   - "Bad continuation": What happens after the move that was actually played (shows the PROBLEM)
   - "Best continuation": What happens after Stockfish's recommended move (shows the SOLUTION)
2. Your job is to explain BOTH continuations step-by-step in a way that's EASY TO FOLLOW AND VISUALIZE
3. USE THE PROVIDED FEN STRINGS (before/after each move) to verify exact piece positions - these are your source of truth
4. ⚠️ ABSOLUTELY DO NOT INVENT OR ADD MOVES - Your job is ONLY to explain the exact moves provided by Stockfish
5. Do NOT suggest alternative variations or calculate additional moves
6. If userColor is provided, personalize your explanations using "you/your" for the user's moves and "opponent" for their opponent's moves

EXPLANATION STYLE - BE CONCRETE AND VISUAL:
- For every move, use the before/after FENs to describe exactly what changed on the board
- For threats: Clearly state WHAT piece on WHAT square threatens WHAT. Example: "Your rook on g4 can now capture their queen on g7"
- For captures: Always explain the full consequence. Example: "After Qxf7, their queen takes your f7 pawn, but now your rook on f1 captures their queen on f7 - you win the queen for just a pawn"
- Use explicit square references: "the knight on c3" not just "the knight"
- Describe the board geometry when relevant: "the diagonal from b2 to g7" or "the open e-file"
- Make cause-and-effect crystal clear: "Because the king moved to h1, the back rank is now undefended, allowing Rd1 checkmate"
- When material is lost, be explicit: "You lose your queen (9 points) for their rook (5 points) - a net loss of 4 points"

Task: 
1. Write a concise overview that: (a) explains WHY the bad move was bad - what's the concrete problem? (b) explains WHY the best move was better - what does it achieve?
2. Explain EACH move in the bad continuation (showing what goes wrong step by step)
3. Explain EACH move in the best continuation (showing why it's a better path)

⚠️ CRITICAL: You MUST return exactly the same number of moves that were provided:
- If you receive 5 moves in badContinuation, return explanations for exactly 5 moves
- If you receive 3 moves in bestContinuation, return explanations for exactly 3 moves
- Do NOT add moves that weren't provided
- Do NOT skip moves that were provided

Respond in valid JSON (no markdown, no code fences):
{
  "explanation": string,
  "badContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ],
  "bestContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ]
}

Rules:
- "explanation": 2-4 sentences answering: (1) WHY was the bad move bad? Be concrete - was it a hanging piece, walking into a tactic, losing material, missing a winning opportunity, weakening the king, etc.? (2) WHY was the best move better? What problem does it avoid or what advantage does it create? Example: "Qxb3 loses the queen - after Rxb3, your opponent simply captures it and you get nothing in return. Instead, d3 advances your passed pawn to the 3rd rank, threatening promotion and keeping pressure on your opponent."
- "badContinuation": For EACH move, explain concretely what's happening. Name pieces and squares. Show the cause-and-effect.
- "bestContinuation": For EACH move, explain what it achieves or prevents, with specific squares and pieces
- Reference the FEN positions to stay accurate - verify which pieces are actually on which squares before explaining
- Be hyper-specific: "your rook on e8 captures their queen on e1" not "rook takes queen"
- Name tactics explicitly when relevant: fork, pin, skewer, discovered attack, back rank weakness, trapped piece, etc.
- ONLY explain what Stockfish calculated - you are a TRANSLATOR, not a chess engine
`.trim();

const googleProvider = createGoogleGenerativeAI({
  apiKey: env.GEMINI_API_KEY,
});

router.post("/explain", requireAuth, async (req: Request, res: Response) => {
  //  const authReq = req as AuthenticatedRequest;

  const parsed = explainRequestSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: "Invalid payload", details: parsed.error.issues });
  }

  const payload = parsed.data;

  try {
    const moveQualityText = payload.moveQuality || "unspecified";

    // Build user context text if userColor is provided
    let userContextText = "";
    if (payload.userColor) {
      userContextText = `User is playing as ${payload.userColor} (${
        payload.userColor === payload.color ? "this is the user's move" : "this is the opponent's move"
      })`;
    }

    // Format continuation moves for the prompt
    const formatContinuation = (moves: z.infer<typeof continuationSchema>[]) => {
      return moves
        .map((c, idx) => {
          const from = c.uci.slice(0, 2);
          const to = c.uci.slice(2, 4);
          return [
            `  Move ${idx + 1}: ${c.san} (${c.color}, from ${from}, to: ${to})`,
            `    Position before: ${c.beforeFen}`,
            `    Position after:  ${c.afterFen}`,
          ].join("\n");
        })
        .join("\n\n");
    };

    const badContinuationLines = formatContinuation(payload.badContinuation);
    const bestContinuationLines = formatContinuation(payload.bestContinuation);

    const userPrompt = [
      "=== POSITION ANALYSIS ===",
      "",
      `Player to move: ${payload.color}`,
      userContextText,
      `Opening: ${[payload.opening, payload.eco].filter(Boolean).join(" • ") || "unknown"}`,
      "",
      "=== MOVE PLAYED (THE BAD MOVE) ===",
      `Position before move (FEN): ${payload.move.beforeFen}`,
      `Move played by ${payload.color}: ${payload.move.san}`,
      `Position after move (FEN): ${payload.move.afterFen}`,
      `Engine evaluation: ${moveQualityText}`,
      "",
      badContinuationLines
        ? [
            "=== WHAT HAPPENS AFTER THE BAD MOVE ===",
            "Stockfish calculated this sequence starting from the bad move position:",
            "",
            badContinuationLines,
            "",
            "☠️ This shows WHY the move is bad - trace through these positions to find the problem!",
          ].join("\n")
        : "",
      "",
      bestContinuationLines
        ? [
            "=== STOCKFISH'S BEST LINE (STARTING WITH THE BEST MOVE) ===",
            "Stockfish calculated this sequence",
            "",
            bestContinuationLines,
            "",
            "✅ This shows WHY the move is best - trace through these positions to find the advantage!",
          ].join("\n")
        : "",
      "",
      "⚠️ YOUR TASK:",
      "1. Compare the two continuations side-by-side using the FENs",
      "2. Explain what goes WRONG in the bad continuation (material loss, tactical blow, bad position?)",
      "3. Explain what goes RIGHT in the best continuation (material gain, better position, safety?)",
      "4. Keep it concise and focused on the KEY difference",
      payload.additionalContext ? `\n=== ADDITIONAL CONTEXT ===\n${payload.additionalContext}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    // Log the prompt for debugging
    console.log("\n" + "=".repeat(80));
    console.log("🤖 SENDING TO LLM:");
    console.log("=".repeat(80));
    console.log(userPrompt);
    console.log("=".repeat(80) + "\n");

    const { output } = await generateText({
      model: googleProvider(MODELS.GEMINI_3_FLASH_PREVIEW),
      system: systemPrompt,
      prompt: userPrompt,
      output: Output.object({ schema: explainResponseSchema }),
      maxRetries: 2,
      temperature: 1, // https://ai.google.dev/gemini-api/docs/gemini-3#temperature
      providerOptions: {
        google: {
          thinkingConfig: {
            includeThoughts: false,
            thinkingLevel: "low",
          },
        },
      },
    });

    // Log the response
    console.log("\n" + "=".repeat(80));
    console.log("✅ LLM RESPONSE:");
    console.log("=".repeat(80));
    console.log("Explanation:", output.explanation);
    console.log("\nBad continuation:", output.badContinuation.length, "moves explained");
    output.badContinuation.forEach((c, idx) => {
      console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
    });
    console.log("\nBest continuation:", output.bestContinuation.length, "moves explained");
    output.bestContinuation.forEach((c, idx) => {
      console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
    });
    console.log("=".repeat(80) + "\n");

    return res.status(200).json(output);
  } catch (err) {
    console.error("Explain route error", err);
    return res.status(500).json({ error: "Failed to generate explanation" });
  }
});

export default router;
