import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText, Output } from "ai";
import { Router, type Request, type Response } from "express";
import { z } from "zod";

import { env } from "#src/config/env";

const router = Router();

const MODELS = {
  GEMINI_3_PRO_PREVIEW: "gemini-3-pro-preview",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

// Evaluation can be either centipawn or mate
const evaluationSchema = z.union([z.object({ cp: z.number() }), z.object({ mate: z.number() })]);

const moveSchema = z.object({
  san: z.string(),
  uci: z.string(),
  beforeFen: z.string(),
  afterFen: z.string(),
  color: z.enum(["white", "black"]),
  evaluation: evaluationSchema.optional(),
});

const explainRequestSchema = z.object({
  move: moveSchema,
  moveQuality: z.enum(["blunder", "mistake", "inaccuracy", "good", "great", "brilliant"]).optional(),
  badContinuation: z.array(moveSchema).optional(),
  bestContinuation: z.array(moveSchema).min(1),
  userColor: z.enum(["white", "black"]).optional(),
  opening: z.string().optional(),
  eco: z.string().optional(),
  additionalContext: z.string().optional(),
});

const explainResponseSchema = z.object({
  explanation: z.string(),
  badContinuation: z
    .array(
      z.object({
        move: z.string(),
        color: z.enum(["white", "black"]),
        reason: z.string(),
      })
    )
    .optional(),
  bestContinuation: z.array(
    z.object({
      move: z.string(),
      color: z.enum(["white", "black"]),
      reason: z.string(),
    })
  ),
});

const systemPrompt = `
You are a chess coach explaining Stockfish's analysis to a student. Your role is to TRANSLATE the engine's evaluation into human understanding, NOT to calculate moves yourself.

## CRITICAL INSTRUCTIONS

1. You will receive TWO continuations, both FRESHLY GENERATED by Stockfish:
   - "Bad continuation": What happens after the move that was actually played (shows the PROBLEM)
   - "Best continuation": What happens after Stockfish's recommended move (shows the SOLUTION)
2. Your job is to explain BOTH continuations step-by-step in a way that's EASY TO FOLLOW AND VISUALIZE
3. USE THE PROVIDED FEN STRINGS (before/after each move) to verify exact piece positions - these are your source of truth
4. ABSOLUTELY DO NOT INVENT OR ADD MOVES - Your job is ONLY to explain the exact moves provided by Stockfish
5. Do NOT suggest alternative variations or calculate additional moves
6. If userColor is provided, personalize your explanations using "you/your" for the user's moves and "opponent" for their opponent's moves

## UNDERSTANDING EVALUATIONS

- Evaluation is in Pawns from White's perspective
- Positive = White is better: +1.5 means White is up about 1.5 pawns
- Negative = Black is better: -2.0 means Black is up about 2 pawns
- Mate scores shown as "M3" (White mates in 3) or "M-3" (Black mates in 3)
- Large eval swings indicate critical moments

## HOW TO PROCESS EACH MOVE

For each move, you receive:
- SAN (move notation) with [CAPTURE] and [CHECK] markers pre-verified
- beforeFen / afterFen (position before and after)
- evaluation (position eval AFTER this move, in pawns)

To understand what a move does:
1. Compare beforeFen to afterFen - what changed?
2. If a piece disappeared from the board, it was captured
3. Look at [CHECK] marker or SAN ending with "+" = check. NO marker/no "+" = NOT check.
4. SAN ends with "#" = checkmate
5. [CAPTURE] marker or SAN contains "x" = capture

## EVERY MOVE HAS A PURPOSE - EXPLAIN THE "WHY"

Every chess move is played for a reason:
1. CAPTURES: Taking material (SAN contains "x" or [CAPTURE] marker)
2. DIRECT THREATS: Piece moves to a square where it attacks an enemy piece (verify from afterFen)
3. DEFENSE: Protecting a piece or escaping an attack
4. POSITIONAL: Better piece placement, controlling key squares
5. FORCING: Limiting opponent's options, gaining tempo

## WHAT THREATS YOU CAN MENTION

ALLOWED - Simple direct attacks you can verify:
- "Queen moves to g3, capturing the pawn and also attacking the bishop on c7" (if you can verify the bishop is on c7 in afterFen and queen on g3 attacks it)
- "Knight jumps to f5, forking the queen and rook" (if you can verify both pieces are attacked)
- "Rook slides to the open file, targeting the weak pawn on d6"

NOT ALLOWED - Complex tactics you cannot verify:
- Claiming a move gives CHECK unless [CHECK] marker or "+" in SAN
- Claiming pins/skewers unless you verify all three pieces are on the exact same line
- Multi-move tactical sequences ("this sets up Qxh7+ next move followed by...")
- Threats that require calculating multiple moves ahead

RULE OF THUMB: You can mention what a piece DIRECTLY attacks after it moves (one-move threats). Do NOT claim check, pins, or complex tactics unless you can verify them.

## STRICT RULES - DO NOT VIOLATE

1. CHECK: A move is check ONLY if marked [CHECK] or SAN ends with "+". No marker/no "+" = not check. NEVER claim otherwise.

2. PINS AND SKEWERS: DO NOT claim a pin/skewer unless you verify all three pieces are on the EXACT SAME LINE. When in doubt, say "attacks" instead of "pins".

3. CAPTURES: Only claim a capture if marked [CAPTURE] or SAN contains "x".

4. GROUNDING: The FEN strings, evaluations, and markers are your source of truth.

## EXPLANATION STYLE

- Use the FENs to verify piece positions
- Be specific: "knight on c3" not just "the knight"
- Explain cause-and-effect clearly
- For material loss, state point values (pawn=1, knight/bishop=3, rook=5, queen=9)
- Reference eval changes to show why moves matter

## YOUR TASK

1. Overview (explanation field): WHY was the bad move bad? WHY is the best move better? Use eval swing if available.
2. Explain EACH move in bad continuation - trace through FENs to find where things go wrong
3. Explain EACH move in best continuation - trace through FENs to find the advantage

Return exactly the same number of moves as provided - no more, no less.

## OUTPUT FORMAT

Respond in valid JSON (no markdown, no code fences):
{
  "explanation": string,
  "badContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ],
  "bestContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ]
}

Keep each reason in badContinuation & bestContinuation to ONE or TWO concise sentences focused on what ACTUALLY HAPPENS because of that move.
If no badContinuation is provided, omit that field.
`.trim();

const googleProvider = createGoogleGenerativeAI({
  apiKey: env.GEMINI_API_KEY,
});

// Type guard for mate evaluation
const isMateEval = (eval_: z.infer<typeof evaluationSchema>): eval_ is { mate: number } => {
  return "mate" in eval_;
};

// Type guard for centipawn evaluation
const isCpEval = (eval_: z.infer<typeof evaluationSchema>): eval_ is { cp: number } => {
  return "cp" in eval_;
};

// Format evaluation for display (converts cp to pawns)
const formatEval = (evaluation: z.infer<typeof evaluationSchema> | undefined): string => {
  if (!evaluation) return "unknown";

  if (isMateEval(evaluation)) {
    const mate = evaluation.mate;
    return mate > 0 ? `M${mate} (White mates in ${mate})` : `M${mate} (Black mates in ${Math.abs(mate)})`;
  }

  if (isCpEval(evaluation)) {
    const pawns = evaluation.cp / 100;
    const sign = pawns >= 0 ? "+" : "";
    return `${sign}${pawns.toFixed(1)} pawns`;
  }

  return "unknown";
};

// Get numeric value for eval comparison (in centipawns, or large number for mate)
const getEvalValue = (evaluation: z.infer<typeof evaluationSchema> | undefined): number | null => {
  if (!evaluation) return null;

  if (isMateEval(evaluation)) {
    return evaluation.mate > 0 ? 10000 - evaluation.mate : -10000 - evaluation.mate;
  }

  if (isCpEval(evaluation)) {
    return evaluation.cp;
  }

  return null;
};

// Format a single move for the prompt
const formatMove = (m: z.infer<typeof moveSchema>, idx: number): string => {
  const from = m.uci.slice(0, 2);
  const to = m.uci.slice(2, 4);
  const evalStr = m.evaluation ? ` [eval: ${formatEval(m.evaluation)}]` : "";
  const isCheck = m.san.endsWith("+") || m.san.endsWith("#");
  const isCapture = m.san.includes("x");

  return [
    `Move ${idx + 1}: ${m.san} (${m.color})${evalStr}`,
    `  ${from} -> ${to}${isCapture ? " [CAPTURE]" : ""}${isCheck ? " [CHECK]" : ""}`,
    `  Position before this move: ${m.beforeFen}`,
    `  Position after this move:  ${m.afterFen}`,
  ].join("\n");
};

router.post("/explain", async (req: Request, res: Response) => {
  const parsed = explainRequestSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: "Invalid payload", details: parsed.error.issues });
  }

  const payload = parsed.data;

  try {
    // Build context strings
    const userContextText = payload.userColor
      ? `You are coaching ${payload.userColor}. Use "you/your" for ${payload.userColor}'s moves, "opponent" for ${
          payload.userColor === "white" ? "black" : "white"
        }'s moves.`
      : "";

    const openingText =
      payload.opening || payload.eco ? `Opening: ${[payload.opening, payload.eco].filter(Boolean).join(" - ")}` : "";

    // Calculate eval swing if we have the data
    const badMoveEvalValue = getEvalValue(payload.move.evaluation);
    const bestFirstMoveEvalValue = getEvalValue(payload.bestContinuation[0]?.evaluation);

    let evalSwingText = "";
    if (badMoveEvalValue !== null && bestFirstMoveEvalValue !== null) {
      const swingCp = Math.abs(badMoveEvalValue - bestFirstMoveEvalValue);
      if (swingCp >= 50) {
        const swingPawns = (swingCp / 100).toFixed(1);
        evalSwingText = `Eval swing: ${formatEval(payload.move.evaluation)} -> ${formatEval(
          payload.bestContinuation[0]?.evaluation
        )} (${swingPawns} pawn difference)`;
      }
    }

    const userPrompt = [
      "=== POSITION ===",
      `${payload.move.color} to move`,
      userContextText,
      openingText,
      "",
      "=== MOVE PLAYED (THE BAD MOVE) ===",
      `Move: ${payload.move.san} (${payload.moveQuality || "unclassified"})`,
      `Before: ${payload.move.beforeFen}`,
      `After: ${payload.move.afterFen}`,
      payload.move.evaluation ? `Eval after this move: ${formatEval(payload.move.evaluation)}` : "",
      evalSwingText,
      "",
      payload.badContinuation && payload.badContinuation.length > 0
        ? [
            "=== BAD CONTINUATION ===",
            "What happens if the game continues from the bad move (shows the PROBLEM):",
            "",
            ...payload.badContinuation.map((m, idx) => formatMove(m, idx)),
            "",
            "Trace through these positions to find where things go wrong.",
          ].join("\n")
        : "",
      "",
      "=== BEST CONTINUATION ===",
      "What Stockfish recommends instead (shows the SOLUTION):",
      "",
      ...payload.bestContinuation.map((m, idx) => formatMove(m, idx)),
      "",
      "Trace through these positions to find what advantage this sequence creates.",
      "",
      payload.additionalContext ? `=== ADDITIONAL CONTEXT ===\n${payload.additionalContext}\n` : "",
      "=== TASK ===",
      "1. OVERVIEW: Compare the two lines. Why does the bad move lose advantage? Why is the best move better?",
      "2. BAD CONTINUATION: Explain each move - what is its purpose? Where does the problem materialize?",
      "3. BEST CONTINUATION: Explain each move - what is its purpose? What advantage is gained?",
      "",
      "REMINDERS:",
      "- Check ONLY if [CHECK] marker present or SAN ends with '+' or '#'",
      "- You CAN mention direct threats (piece X attacks piece Y) if verifiable from afterFen",
      "- [CAPTURE] and [CHECK] markers are pre-verified - trust them",
      "- Return exactly the same number of moves as provided",
    ]
      .filter(Boolean)
      .join("\n");

    console.log("\n" + "=".repeat(80));
    console.log("SENDING TO LLM:");
    console.log("=".repeat(80));
    console.log(userPrompt);
    console.log("=".repeat(80) + "\n");

    const { output } = await generateText({
      model: googleProvider(MODELS.GEMINI_3_FLASH_PREVIEW),
      system: systemPrompt,
      prompt: userPrompt,
      output: Output.object({ schema: explainResponseSchema }),
      maxRetries: 2,
      temperature: 1, // https://ai.google.dev/gemini-api/docs/gemini-3#temperature
      providerOptions: {
        google: {
          thinkingConfig: {
            includeThoughts: false,
            thinkingLevel: "low",
          },
        },
      },
    });

    console.log("\n" + "=".repeat(80));
    console.log("LLM RESPONSE:");
    console.log("=".repeat(80));
    console.log("Explanation:", output.explanation);
    if (output.badContinuation) {
      console.log("\nBad continuation:", output.badContinuation.length, "moves");
      output.badContinuation.forEach((c, idx) => {
        console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
      });
    }
    console.log("\nBest continuation:", output.bestContinuation.length, "moves");
    output.bestContinuation.forEach((c, idx) => {
      console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
    });
    console.log("=".repeat(80) + "\n");

    return res.status(200).json(output);
  } catch (err) {
    console.error("Explain route error", err);
    return res.status(500).json({ error: "Failed to generate explanation" });
  }
});

export default router;
