import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText } from "ai";
import { Router, type Request, type Response } from "express";
import { z } from "zod";

import { env } from "#src/config/env";
import { requireAuth } from "#src/middlewares/auth";

const router = Router();

const MODELS = {
  GEMINI_3_PRO_PREVIEW: "gemini-3-pro-preview",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
};

const continuationSchema = z.object({
  san: z.string(),
  beforeFen: z.string(),
  afterFen: z.string(),
  color: z.enum(["white", "black"]),
});

const explainRequestSchema = z.object({
  move: z.object({
    san: z.string(),
    beforeFen: z.string(),
    afterFen: z.string(),
  }),
  badContinuation: z.array(continuationSchema),
  bestContinuation: z.array(continuationSchema).min(1),
  color: z.enum(["white", "black"]),
  userColor: z.enum(["white", "black"]).optional(), // Color the user is playing as
  moveQuality: z.enum(["blunder", "mistake", "inaccuracy", "good", "brilliant"]).optional(),
  mate: z.number().optional().default(0),
  opening: z.string().optional(),
  eco: z.string().optional(),
  additionalContext: z.string().optional(),
});

const explainResponseSchema = z.object({
  explanation: z.string(),
  badContinuation: z.array(
    z.object({
      move: z.string(),
      color: z.enum(["white", "black"]),
      reason: z.string(),
    })
  ),
  bestContinuation: z.array(
    z.object({
      move: z.string(),
      color: z.enum(["white", "black"]),
      reason: z.string(),
    })
  ),
});

const systemPrompt = `
You are a chess coach explaining Stockfish's analysis to a student. Your role is to TRANSLATE the engine's evaluation into human understanding, NOT to calculate moves yourself.

CRITICAL INSTRUCTIONS:
1. You will receive TWO continuations, both FRESHLY GENERATED by Stockfish:
   - "Bad continuation": What happens after the move that was actually played (shows the THREAT/PROBLEM)
   - "Best continuation": What happens after Stockfish's recommended move (shows the SOLUTION)
2. Your job is to explain BOTH continuations step-by-step
3. Parse each FEN string character by character to understand piece positions
4. ⚠️ ABSOLUTELY DO NOT INVENT OR ADD MOVES - Your job is ONLY to explain the exact moves provided by Stockfish
5. Do NOT suggest alternative variations or calculate additional moves
6. If userColor is provided, personalize your explanations using "you/your" for the user's moves and "opponent" for their opponent's moves

Task: 
1. Write a concise overview comparing both lines
2. Explain EACH move in the bad continuation (showing why it's a threat)
3. Explain EACH move in the best continuation (showing why it's better)

⚠️ CRITICAL: You MUST return exactly the same number of moves that were provided:
- If you receive 5 moves in badContinuation, return explanations for exactly 5 moves
- If you receive 3 moves in bestContinuation, return explanations for exactly 3 moves
- Do NOT add moves that weren't provided
- Do NOT skip moves that were provided

Respond in valid JSON (no markdown, no code fences):
{
  "explanation": string,
  "badContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ],
  "bestContinuation": [
    { "move": string, "color": "white" | "black", "reason": string }
  ]
}

Rules:
- "explanation": A brief overview (2-4 sentences) comparing the two lines at a high level
- "badContinuation": Take EACH move from the provided bad continuation and explain WHY it's dangerous/problematic
- "bestContinuation": Take EACH move from the provided best continuation and explain WHY it's better/safer
- Be specific with piece locations (e.g., "the rook on e8" not "a rook")
- Focus on: material loss/gain, tactical threats (forks, pins, discovered attacks), king safety, piece activity
- Use the FENs to verify piece positions - DO NOT make assumptions
- ONLY explain what Stockfish calculated - you are a TRANSLATOR, not a chess engine
`.trim();

function stripCodeFences(text: string): string {
  const trimmed = text.trim();
  if (trimmed.startsWith("```")) {
    const fenceEnd = trimmed.indexOf("```", 3);
    if (fenceEnd !== -1) {
      return trimmed.slice(trimmed.indexOf("\n") + 1, fenceEnd).trim();
    }
  }
  return trimmed;
}

const googleProvider = createGoogleGenerativeAI({
  apiKey: env.GEMINI_API_KEY,
});

router.post("/explain", requireAuth, async (req: Request, res: Response) => {
  //  const authReq = req as AuthenticatedRequest;

  const parsed = explainRequestSchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({ error: "Invalid payload", details: parsed.error.issues });
  }

  const payload = parsed.data;

  try {
    const moveQualityText = payload.moveQuality || "unspecified";

    // Build user context text if userColor is provided
    let userContextText = "";
    if (payload.userColor) {
      userContextText = `User is playing as ${payload.userColor} (${
        payload.userColor === payload.color ? "this is the user's move" : "this is the opponent's move"
      })`;
    }

    // Format continuation moves for the prompt
    const formatContinuation = (moves: z.infer<typeof continuationSchema>[]) => {
      return moves
        .map((c, idx) => {
          return [
            `  Move ${idx + 1}: ${c.san} (${c.color})`,
            `    Position before: ${c.beforeFen}`,
            `    Position after:  ${c.afterFen}`,
          ].join("\n");
        })
        .join("\n\n");
    };

    const badContinuationLines = formatContinuation(payload.badContinuation);
    const bestContinuationLines = formatContinuation(payload.bestContinuation);

    const userPrompt = [
      "=== POSITION ANALYSIS ===",
      "",
      `Player to move: ${payload.color}`,
      userContextText,
      `Opening: ${[payload.opening, payload.eco].filter(Boolean).join(" • ") || "unknown"}`,
      "",
      "=== MOVE PLAYED (THE BAD MOVE) ===",
      `Position before move (FEN): ${payload.move.beforeFen}`,
      `Move played by ${payload.color}: ${payload.move.san}`,
      `Position after move (FEN): ${payload.move.afterFen}`,
      `Engine evaluation: ${moveQualityText}`,
      "",
      badContinuationLines
        ? [
            "=== WHAT HAPPENS AFTER THE BAD MOVE ===",
            "Stockfish calculated this sequence starting from the bad move position:",
            "",
            badContinuationLines,
            "",
            "☠️ This shows WHY the move is bad - trace through these positions to find the problem!",
          ].join("\n")
        : "",
      "",
      bestContinuationLines
        ? [
            "=== STOCKFISH'S BEST LINE (STARTING WITH THE BEST MOVE) ===",
            "Stockfish calculated this sequence",
            "",
            bestContinuationLines,
            "",
            "✅ This shows WHY the move is best - trace through these positions to find the advantage!",
          ].join("\n")
        : "",
      "",
      "⚠️ YOUR TASK:",
      "1. Compare the two continuations side-by-side using the FENs",
      "2. Explain what goes WRONG in the bad continuation (material loss, tactical blow, bad position?)",
      "3. Explain what goes RIGHT in the best continuation (material gain, better position, safety?)",
      "4. Keep it concise and focused on the KEY difference",
      payload.additionalContext ? `\n=== ADDITIONAL CONTEXT ===\n${payload.additionalContext}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    // Log the prompt for debugging
    console.log("\n" + "=".repeat(80));
    console.log("🤖 SENDING TO LLM:");
    console.log("=".repeat(80));
    console.log(userPrompt);
    console.log("=".repeat(80) + "\n");

    const structuredResult = await generateText({
      model: googleProvider(MODELS.GEMINI_3_FLASH_PREVIEW),
      system: systemPrompt,
      prompt: userPrompt,
      maxRetries: 2,
      temperature: 0.2,
      providerOptions: {
        google: {
          thinkingConfig: {
            includeThoughts: false,
            thinkingLevel: "low",
          },
        },
      },
    });

    const cleanedText = stripCodeFences(structuredResult.text);
    const parsedJson = JSON.parse(cleanedText);
    const parsedResult = explainResponseSchema.safeParse(parsedJson);
    if (!parsedResult.success) {
      return res.status(500).json({ error: "LLM returned invalid format", details: parsedResult.error.issues });
    }

    // Log the response
    console.log("\n" + "=".repeat(80));
    console.log("✅ LLM RESPONSE:");
    console.log("=".repeat(80));
    console.log("Explanation:", parsedResult.data.explanation);
    console.log("\nBad continuation:", parsedResult.data.badContinuation.length, "moves explained");
    parsedResult.data.badContinuation.forEach((c, idx) => {
      console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
    });
    console.log("\nBest continuation:", parsedResult.data.bestContinuation.length, "moves explained");
    parsedResult.data.bestContinuation.forEach((c, idx) => {
      console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
    });
    console.log("=".repeat(80) + "\n");

    return res.status(200).json(parsedResult.data);
  } catch (err) {
    console.error("Explain route error", err);
    return res.status(500).json({ error: "Failed to generate explanation" });
  }
});

export default router;
