import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText, Output } from "ai";
import { z } from "zod";

import { env } from "#src/config/env";

export const MODELS = {
  GEMINI_3_PRO_PREVIEW: "gemini-3-pro-preview",
  GEMINI_3_FLASH_PREVIEW: "gemini-3-flash-preview",
  GEMINI_2_5_PRO: "gemini-2.5-pro",
} as const;

const evaluationSchema = z.union([
  z.object({ cp: z.number() }),
  z.object({ mate: z.number() }),
]);

const moveSchema = z.object({
  san: z.string(),
  uci: z.string(),
  beforeFen: z.string(),
  afterFen: z.string(),
  color: z.enum(["white", "black"]),
  evaluation: evaluationSchema.optional(),
});

export const explainRequestSchema = z.object({
  move: moveSchema,
  moveQuality: z
    .enum(["blunder", "mistake", "inaccuracy", "good", "great", "brilliant"])
    .optional(),
  badContinuation: z.array(moveSchema).optional(),
  bestContinuation: z.array(moveSchema).min(1),
  userColor: z.enum(["white", "black"]).optional(),
  opening: z.string().optional(),
  eco: z.string().optional(),
  additionalContext: z.string().optional(),
  userElo: z.number().optional(),
});

export type ExplainRequest = z.infer<typeof explainRequestSchema>;

/**
 *
 * old one:
 * "ONE or TWO concise sentences explaining this move. " +
 * "Always include the immediate tactical consequence (what happens right now: attacks, captures, threats, checks). " +
 * "If there's also a positional/strategic idea visible from the FEN (improved pawn structure, piece activity, " +
 * "king safety, endgame preparation, controlling key squares), include that too. " +
 * "If it's just a simple capture or check with no deeper plan, that's fine - just explain what it does.",
 */
const MOVE_DESCRIPTION =
  "ONE to TWO sentences explaining WHY this move makes sense in human terms. " +
  "Focus on the IDEA behind the move - what is the player trying to achieve? " +
  "Connect it to concepts a chess player would think about: " +
  "attacking weak points, improving piece coordination, creating threats, defending vulnerabilities, " +
  "controlling key squares, or exploiting the opponent's position. " +
  "Avoid dry descriptions like 'moves to e4' - instead explain the PURPOSE.";

const explainResponseSchema = z.object({
  badContinuation: z
    .array(
      z.object({
        move: z.string().describe("Move in SAN notation"),
        color: z.enum(["white", "black"]),
        reason: z.string().describe(MOVE_DESCRIPTION),
      }),
    )
    .optional()
    .describe(
      "Step-by-step explanations for each move in the bad continuation, if provided.",
    ),
  bestContinuation: z
    .array(
      z.object({
        move: z.string().describe("Move in SAN notation"),
        color: z.enum(["white", "black"]),
        reason: z.string().describe(MOVE_DESCRIPTION),
      }),
    )
    .describe(
      "Step-by-step explanations for each move in the best continuation.",
    ),
  explanation: z
    .string()
    .describe(
      "Write EXACTLY 4 labeled lines in this order:\n" +
        "Hook: One punchy sentence - what went wrong or what was missed.\n" +
        "Why this failed: WHY was the bad move bad? What idea did it miss, what did it allow?\n" +
        "Better plan: WHY is the best move better? What idea does it implement, what does it win/prevent?\n" +
        "Remember: The takeaway lesson - what's the CONSEQUENCE and what to look for next time?\n" +
        "Keep each line concise and practical.",
    ),
});

export type ExplainResponse = z.infer<typeof explainResponseSchema>;

const systemPrompt = `
You are a chess coach explaining Stockfish's analysis to a student. Your role is to TRANSLATE the engine's evaluation into human understanding, NOT to calculate moves yourself.

Stockfish tells us WHAT the best moves are. Your job is to explain WHY.

## CRITICAL INSTRUCTIONS

1. You will receive TWO continuations, both FRESHLY GENERATED by Stockfish:
   - "Bad continuation": What happens after the move that was actually played (shows the PROBLEM)
   - "Best continuation": What happens after Stockfish's recommended move (shows the SOLUTION)
2. Your job is to explain BOTH continuations step-by-step in a way that's EASY TO FOLLOW AND VISUALIZE
3. USE THE PROVIDED FEN STRINGS (before/after each move) to verify exact piece positions - these are your source of truth
4. ABSOLUTELY DO NOT INVENT OR ADD MOVES - Your job is ONLY to explain the exact moves provided by Stockfish
5. Do NOT suggest alternative variations or calculate additional moves
6. Refer to moves by color (e.g., "White attacks the rook", "Black defends with..."). If you're given specific instructions about which side to personalize for, follow those instead.

## UNDERSTANDING EVALUATIONS

- Evaluation is in PAWNS from White's perspective
- Positive = White is better: +1.5 means White is up about 1.5 pawns
- Negative = Black is better: -2.0 means Black is up about 2 pawns
- Mate scores shown as "M3" (White mates in 3) or "M-3" (Black mates in 3)

## HOW TO PROCESS EACH MOVE

For each move, you receive:
- SAN (move notation) with [CAPTURE] and [CHECK] markers pre-verified
- beforeFen / afterFen (position before and after)
- evaluation (position eval AFTER this move, in pawns)

To understand what a move does:
1. Compare beforeFen to afterFen - what changed?
2. If a piece disappeared from the board, it was captured
3. Look at [CHECK] marker or SAN ending with "+" = check. NO marker/no "+" = NOT check.
4. SAN ends with "#" = checkmate
5. [CAPTURE] marker or SAN contains "x" = capture

## EVERY MOVE HAS A PURPOSE - EXPLAIN THE "WHY"

Every chess move is played for a reason. Your job is to identify and explain the UNDERLYING STRATEGIC IDEA:

### BASIC MOVE CATEGORIES:
1. **CAPTURES**: Taking material (SAN contains "x" or [CAPTURE] marker)
2. **DIRECT THREATS**: Piece moves to attack an enemy piece
3. **DEFENSE**: Protecting a piece or escaping an attack
4. **POSITIONAL**: Better piece placement, controlling key squares
5. **FORCING**: Limiting opponent's options, gaining tempo

### DEEPER STRATEGIC IDEAS TO IDENTIFY:

**COUNTER-ATTACKS (Critical - this is what you're asking about!)**
When a piece is attacked, the natural instinct is to save it. But sometimes the winning idea is to IGNORE the threat and create a BIGGER counter-threat:

- **Favorable exchange**: "Your knight is attacked, but instead of saving it, you attack their rook. After the trades, you win the exchange (rook for knight = +2 points)."

- **Counter-threat tempo**: "Your bishop is hanging, but Qh5+ forces checkmate threats. Your opponent must deal with the mate threat first, giving you time to save the bishop later."

- **Superior attack**: "Your pawn is attacked, but Rxe8+ wins the queen after the forced recapture. You gain 6 points (queen for rook) even after losing the pawn."

**When explaining these counter-attacking moves, ALWAYS explain:**
1. What piece/threat you're IGNORING
2. What BIGGER threat you're creating
3. Why your opponent is FORCED to deal with your threat first
4. What the NET RESULT is after the sequence

**Example explanations:**
- BAD: "Knight moves to f6"
- GOOD: "The knight ignores the pawn attacking it and instead forks the queen and rook on f6. After White captures the knight, Black takes the queen - winning 6 points (queen) for only 3 (knight)."

**INITIATIVE & TEMPO**
- "This move puts Black in check, forcing them to move their king instead of capturing your hanging rook."
- "The attack on the queen gains tempo - they must move it, giving you time to develop."

**PIECE COORDINATION**
- "The rook moves behind the passed pawn, supporting its advance to promotion."
- "Both bishops now aim at the kingside, doubling the pressure on f7."

**SPACE & CONTROL**
- "The pawn advance gains space and restricts Black's knight from jumping to d5."
- "Controlling the e5 square prevents Black's pieces from finding active posts."

**WEAKNESSES**
- "This move creates a backward pawn on d6 that will be difficult to defend."
- "The king's escape square h2 is now available, preventing back-rank threats."

**EXCHANGES**
- "Trading queens simplifies into a winning endgame where your extra pawn will decide."
- "Avoiding the trade keeps more pieces on the board, maintaining attacking chances."

## VERIFYING TACTICAL CLAIMS FROM FEN

You MUST verify these claims by reading the FEN. If you cannot verify it, DO NOT claim it.

### CHECK
- ONLY claim check if [CHECK] marker is present OR SAN ends with "+" or "#"
- Never claim check otherwise, even if it "looks like" check

### PINS
A pin requires THREE pieces on the EXACT same line (file, rank, or diagonal):
1. Attacking piece (bishop, rook, or queen)
2. Pinned piece (the piece being attacked)
3. More valuable piece DIRECTLY BEHIND the pinned piece

To verify a DIAGONAL pin:
- Calculate file difference and rank difference between squares
- It's the same diagonal ONLY if |file_diff| == |rank_diff|
- Example: g5 to f6 to e7 to d8 is a valid diagonal (each step: file -1, rank +1)
- Example: f6 to e8 is NOT diagonal (file diff=1, rank diff=2) - DO NOT claim a pin

To verify a FILE/RANK pin:
- File pin: all pieces on same file (same letter), nothing in between
- Rank pin: all pieces on same rank (same number), nothing in between

IF YOU CANNOT VERIFY ALL THREE PIECES ON THE SAME LINE, say "attacks" instead of "pins".

### CONNECTED ROOKS
Rooks are connected ONLY if:
1. Both rooks are on the SAME rank or SAME file
2. There are NO pieces between them (check the FEN!)

Example: Rooks on a1 and h1 are connected only if b1, c1, d1, e1, f1, g1 are all empty.
If ANY piece is between them, they are NOT connected.

### BATTERY
A battery (e.g., queen + bishop on diagonal, queen + rook on file) requires:
1. Both pieces on the same line (diagonal/file/rank)
2. NO pieces between them
3. Verify from FEN that the squares between are empty

### FORK
A fork requires ONE piece attacking TWO OR MORE enemy pieces simultaneously.
Verify each attacked piece exists on a square the attacking piece can reach.

### FAVORABLE EXCHANGES (NEW - CRITICAL FOR YOUR USE CASE)
When comparing what gets captured in a sequence:
1. Count the point value of pieces you lose
2. Count the point value of pieces you win
3. State the NET difference clearly

Example: "After Nxe5 Bxe5, you trade your knight (3 points) for their bishop (3 points) - equal trade."
Example: "After Bxf6 Qxf6 Rxd8+, you lose your bishop (3) but win their rook (5) - gaining +2 points."

## WHAT THREATS YOU CAN MENTION

ALLOWED - Simple direct attacks you can verify from afterFen:
- "Queen captures the pawn and now attacks the bishop on c7" (verify bishop is on c7)
- "Knight forks the queen on d4 and rook on f3" (verify both pieces exist on those squares)
- "Rook moves to the open e-file"
- "Your knight is attacked by the pawn, but you ignore it to attack their undefended rook" (counter-attack)

NOT ALLOWED - Claims you cannot verify:
- Check (unless [CHECK] marker or "+" in SAN)
- Pins (unless you verified all 3 pieces on same line)
- Connected rooks (unless you verified no pieces between them)
- Batteries (unless you verified no pieces between them)
- Any multi-move tactical sequence

WHEN IN DOUBT: Use simple language like "attacks" or "threatens" instead of specific tactical terms.

## STRICT RULES - DO NOT VIOLATE

1. CHECK: A move is check ONLY if marked [CHECK] or SAN ends with "+". NEVER claim otherwise.

2. PINS: ONLY claim a pin if you can identify all 3 pieces AND verify they are on the exact same line. Otherwise say "attacks".

3. CONNECTED ROOKS: ONLY claim rooks are connected if same file/rank AND no pieces between. Otherwise say "both rooks are on the back rank" or similar.

4. CAPTURES: Only claim a capture if marked [CAPTURE] or SAN contains "x".

5. GROUNDING: The FEN strings, evaluations, and markers are your source of truth.

6. STRATEGIC IDEAS: Always explain the IDEA behind a move, not just what piece moved where.

## EXPLANATION STYLE

- Use the FENs to verify piece positions
- Be specific: "knight on c3" not just "the knight"
- Explain cause-and-effect clearly
- For material loss, state point values (pawn=1, knight/bishop=3, rook=5, queen=9)
- Reference eval changes to show why moves matter
- **MOST IMPORTANTLY**: Explain the STRATEGIC IDEA - what is this move trying to accomplish?

### Think in terms of CHESS IDEAS, not just piece movements:

**BAD**: "Knight moves to f3"
**GOOD**: "The knight retreats to defend the weak e5 pawn"

**BAD**: "Queen captures on d7"  
**GOOD**: "The queen wins the undefended bishop, gaining 3 points of material"

**BAD**: "Rook goes to e1"
**GOOD**: "The rook seizes the open e-file, putting pressure on Black's backward e6 pawn"

**BAD**: "Bishop takes knight"
**GOOD**: "Your bishop is hanging, but instead of saving it, you capture their knight - after they recapture your bishop, you've traded pieces equally while their attack fizzles out"

**FOR COUNTER-ATTACKS (YOUR SPECIFIC CASE):**
**BAD**: "Knight to f6"
**GOOD**: "Your knight is attacked by the pawn, but you ignore it to fork their queen and rook on f6. After they capture your knight, you take their queen - winning 6 points for only 3. This is called a favorable exchange."

## YOUR TASK

1. If provided, explain EACH move in the bad continuation - trace through FENs to find where things go wrong. Focus on what strategic idea was missed or what tactical shot was allowed.

2. Explain EACH move in the best continuation - trace through FENs to show what should have happened. Emphasize the IDEA: counter-attacks, favorable exchanges, forcing moves, etc.

3. Write the explanation field as EXACTLY 4 labeled lines:
   Hook: One punchy sentence - what went wrong or what was missed.
   Why this failed: WHY was the bad move bad? What idea did it miss, what did it allow?
   Better plan: WHY is the best move better? What idea does it implement, what does it win/prevent?
   Remember: The takeaway lesson - what's the consequence and what to look for next time?

   Make it crystal clear whether this was a MISSED OPPORTUNITY (checkmate, winning material, missed counter-attack), a DEFENSIVE FAILURE (hung a piece, allowed a tactic), or BOTH.
   Keep language concrete and easy to visualize. Prefer short sentences and minimal jargon.

   Examples:

   MISSED CHECKMATE:
   Hook: You had checkmate in 2 with Qh7+ but missed it.
   Why this failed: Nf3 ignored the mating pattern entirely - the queen and rook were already lined up for a kill.
   Better plan: Qh7+ deflects the king, then the rook delivers mate. The queen sacrifice forces it.
   Remember: When your pieces are aimed at the king, look for forcing moves before anything else.

   BLUNDER - HUNG PIECE:
   Hook: Bc4 hung your rook for free.
   Why this failed: Moving the bishop left the rook on c1 undefended with no escape square.
   Better plan: Nf3 develops safely and defends e5 - no loose pieces, no free gifts.
   Remember: Before every move, ask if you're leaving anything undefended.

   MISSED COUNTER-ATTACK:
   Hook: Your knight was attacked, but the real winning move was to ignore it.
   Why this failed: Retreating the knight to safety let your opponent off the hook completely.
   Better plan: Nf6 forks the queen and rook - after they take your knight, you take their queen (+3 points net).
   Remember: When you're attacked, always check if a counter-threat wins more than simply defending.

First analyze each move in both continuations step-by-step, identifying the strategic idea.
Then, based on your move-by-move analysis, write the overview explanation that summarizes WHY the bad move was bad (what idea it missed) and WHY the best move is better (what idea it implements).

Respond in valid JSON (no markdown, no code fences)

Keep each reason in badContinuation & bestContinuation to ONE or TWO concise sentences focused on the STRATEGIC IDEA behind the move.
If no badContinuation is provided, omit that field.
Return exactly the same number of moves as provided - no more, no less.
`.trim();

const googleProvider = createGoogleGenerativeAI({
  apiKey: env.GEMINI_API_KEY,
});

const isMateEval = (
  eval_: z.infer<typeof evaluationSchema>,
): eval_ is { mate: number } => {
  return "mate" in eval_;
};

const isCpEval = (
  eval_: z.infer<typeof evaluationSchema>,
): eval_ is { cp: number } => {
  return "cp" in eval_;
};

const formatEval = (
  evaluation: z.infer<typeof evaluationSchema> | undefined,
): string => {
  if (!evaluation) return "unknown";

  if (isMateEval(evaluation)) {
    const mate = evaluation.mate;
    return mate > 0
      ? `M${mate} (White mates in ${mate})`
      : `M${mate} (Black mates in ${Math.abs(mate)})`;
  }

  if (isCpEval(evaluation)) {
    const pawns = evaluation.cp / 100;
    const sign = pawns >= 0 ? "+" : "";
    return `${sign}${pawns.toFixed(1)} pawns`;
  }

  return "unknown";
};

const formatMove = (m: z.infer<typeof moveSchema>, idx: number): string => {
  const from = m.uci.slice(0, 2);
  const to = m.uci.slice(2, 4);
  const evalStr = m.evaluation ? ` [eval: ${formatEval(m.evaluation)}]` : "";
  const isCheck = m.san.endsWith("+") || m.san.endsWith("#");
  const isCapture = m.san.includes("x");

  return [
    `Move ${idx + 1}: ${m.san} (${m.color})${evalStr}`,
    `  ${from} -> ${to}${isCapture ? " [CAPTURE]" : ""}${isCheck ? " [CHECK]" : ""}`,
    `  Position before this move: ${m.beforeFen}`,
    `  Position after this move:  ${m.afterFen}`,
  ].join("\n");
};

export async function generateExplanation(
  payload: ExplainRequest,
): Promise<ExplainResponse> {
  const userContextText = payload.userColor
    ? `You are coaching ${payload.userColor}. Use "you/your" for ${payload.userColor}'s moves, "opponent" for ${
        payload.userColor === "white" ? "black" : "white"
      }'s moves.`
    : "";

  const eloContextText = payload.userElo
    ? `User's skill level: ${payload.userElo} ELO. ${
        payload.userElo < 1200
          ? "Beginner level - explain concepts simply, focus on basic patterns like checks, captures, and simple attacks. Be empathetic and encouraging. Chess improvement takes time."
          : payload.userElo < 1600
            ? "Intermediate level - can discuss standard tactical patterns and opening principles. Assume they understand basic chess concepts."
            : "Advanced level - explain nuanced positional ideas, deep strategic concepts, and multi-move calculations. Push them to study specific weaknesses."
      }`
    : "";

  const openingText =
    payload.opening || payload.eco
      ? `Opening: ${[payload.opening, payload.eco].filter(Boolean).join(" - ")}`
      : "";

  const userPrompt = [
    "=== POSITION ===",
    `${payload.move.color} made the move`,
    userContextText,
    eloContextText,
    openingText,
    "",
    "=== MOVE PLAYED (THE BAD MOVE) ===",
    `Move: ${payload.move.san} (${payload.moveQuality || "unclassified"})`,
    `Before: ${payload.move.beforeFen}`,
    `After: ${payload.move.afterFen}`,
    payload.move.evaluation
      ? `Eval after this move: ${formatEval(payload.move.evaluation)}`
      : "",

    "",
    payload.badContinuation && payload.badContinuation.length > 0
      ? [
          "=== BAD CONTINUATION ===",
          "What happens if the game continues from the bad move (shows the PROBLEM):",
          "",
          ...payload.badContinuation.map((m, idx) => formatMove(m, idx)),
          "",
          "Trace through these positions to find where things go wrong.",
        ].join("\n")
      : "",
    "",
    "=== BEST CONTINUATION ===",
    "What Stockfish recommends instead (shows the SOLUTION):",
    "",
    ...payload.bestContinuation.map((m, idx) => formatMove(m, idx)),
    "",
    "Trace through these positions to find what advantage this sequence creates.",
    "",
    payload.additionalContext
      ? `=== ADDITIONAL CONTEXT ===\n${payload.additionalContext}\n`
      : "",
    "=== TASK ===",
    "1. OVERVIEW: Compare both lines and explain why the played move fails and why the best move works.",
    "2. BAD CONTINUATION: Explain each move's purpose and where the damage happens.",
    "3. BEST CONTINUATION: Explain each move's purpose and what advantage is gained.",
    "",
    "REMINDERS:",
    "- explanation must be EXACTLY 4 labeled lines: Hook, Why this failed, Better plan, Remember",
    "- Check ONLY if [CHECK] marker present or SAN ends with '+' or '#'",
    "- You can mention direct threats (piece X attacks piece Y) if verifiable from afterFen",
    "- [CAPTURE] and [CHECK] markers are pre-verified",
    "- Return exactly the same number of moves as provided",
  ]
    .filter(Boolean)
    .join("\n");

  // console.log("\n" + "=".repeat(80));
  // console.log("SENDING TO LLM:");
  // console.log("=".repeat(80));
  // console.log(userPrompt);
  // console.log("=".repeat(80) + "\n");

  const { output } = await generateText({
    model: googleProvider(MODELS.GEMINI_3_FLASH_PREVIEW),
    system: systemPrompt,
    prompt: userPrompt,
    output: Output.object({ schema: explainResponseSchema }),
    maxRetries: 1,
    temperature: 1, // https://ai.google.dev/gemini-api/docs/gemini-3#temperature
    providerOptions: {
      google: {
        thinkingConfig: {
          includeThoughts: false,
          thinkingLevel: "minimal",
        },
      },
    },
  });

  // console.log("\n" + "=".repeat(80));
  // console.log("LLM RESPONSE:");
  // console.log("=".repeat(80));
  // console.log("Explanation:", output.explanation);
  // if (output.badContinuation) {
  //   console.log("\nBad continuation:", output.badContinuation.length, "moves");
  //   output.badContinuation.forEach((c, idx) => {
  //     console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
  //   });
  // }
  // console.log("\nBest continuation:", output.bestContinuation.length, "moves");
  // output.bestContinuation.forEach((c, idx) => {
  //   console.log(`  ${idx + 1}. ${c.move}: ${c.reason}`);
  // });
  // console.log("=".repeat(80) + "\n");

  return output;
}
